export const defaultData = [
    {
        name: 'Tanner',
        lastName: 'Linsley',
        age: 24,
        status: 'Activo',
    },
    {
        name: 'Marcus',
        lastName: 'Lawos',
        age: 18,
        status: 'Inactivo',
    },
    {
        name: 'Bertha',
        lastName: 'Clegain',
        age: 18,
        status: 'Inactivo',
    },
    {
        name: 'Martha',
        lastName: 'Gordom',
        age: 18,
        status: 'Inactivo',
    },
    {
        name: 'Luis',
        lastName: 'Foxcius',
        age: 18,
        status: 'Activo',
    },
    {
        name: 'Jerom',
        lastName: 'Maison',
        age: 18,
        status: 'Activo',
    },
    {
        name: 'Clara',
        lastName: 'Valezca',
        age: 18,
        status: 'Activo',
    },
    {
        name: 'Lei',
        lastName: 'Doggerti',
        age: 18,
        status: 'Inactivo',
    },
    {
        name: 'Lei',
        lastName: 'Valezca',
        age: 18,
        status: 'Activo',
    },
    {
        name: 'Luis',
        lastName: 'Doggerti',
        age: 18,
        status: 'Activo',
    },
    {
        name: 'Jerom',
        lastName: 'Maison',
        age: 18,
        status: 'Activo',
    },
    {
        name: 'Pedro',
        lastName: 'Wen',
        age: 18,
        status: 'Inactivo',
    },
    {
        name: 'Tanner',
        lastName: 'Linsley',
        age: 24,
        status: 'Activo',
    },
    {
        name: 'Marcus',
        lastName: 'Lawos',
        age: 18,
        status: 'Activo',
    },
    {
        name: 'Bertha',
        lastName: 'Clegain',
        age: 18,
        status: 'Inactivo',
    },
    {
        name: 'Martha',
        lastName: 'Gordom',
        age: 18,
        status: 'Inactivo',
    },
    {
        name: 'Luis',
        lastName: 'Foxcius',
        age: 18,
        status: 'Activo',
    },
    {
        name: 'Jerom',
        lastName: 'Maison',
        age: 18,
        status: 'Activo',
    },
    {
        name: 'Clara',
        lastName: 'Valezca',
        age: 18,
        status: 'Activo',
    },
    {
        name: 'Lei',
        lastName: 'Doggerti',
        age: 18,
        status: 'Activo',
    },
    {
        name: 'Lei',
        lastName: 'Valezca',
        age: 18,
        status: 'Activo',
    },
    {
        name: 'Luis',
        lastName: 'Doggerti',
        age: 18,
        status: 'Activo',
    },
    {
        name: 'Jerom',
        lastName: 'Maison',
        age: 18,
        status: 'Inactivo',
    },
    {
        name: 'Pedro',
        lastName: 'Wen',
        age: 18,
        status: 'Activo',
    },
]